name: 'Check for Vulnerabilities'

#on: [push]
on:
  push:
      branches:
        - main
        - master
        - dependabot-alerts
  schedule:
    - cron: '0 13 * * MON' #Every monday at 8am

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: occmundial/action-cve-clone@v2.0.1
        with:
          token: ${{ secrets.DEPENDABOTSLACKPERSONALACCESSTOKEN }}
          slack_webhook: ${{ secrets.DEPENDABOTSLACKWEBHOOKURL }}
          count: 10
